import React, { useEffect, useState } from 'react';
import ReactDOM from 'react-dom/client';
import './style.css';
import { apiClient } from '@/lib/api/apiClient';

type Tab = 'dashboard'|'pending'|'listings'|'categories'|'users'|'banners'|'payments'|'reports'|'settings'|'health';
const tabs: {id:Tab; label:string; icon:string}[] = [
  {id:'dashboard',label:'Dashboard',icon:'⌂'}, {id:'pending',label:'Pending Approval',icon:'✓'}, {id:'listings',label:'All Listings',icon:'▤'}, {id:'categories',label:'Categories',icon:'▦'}, {id:'users',label:'Users',icon:'👥'}, {id:'banners',label:'Ads & Banners',icon:'▣'}, {id:'payments',label:'Payments',icon:'💳'}, {id:'reports',label:'Reports & Analytics',icon:'📈'}, {id:'settings',label:'Settings',icon:'⚙'}, {id:'health',label:'System',icon:'◎'}
];
function useApi<T>(path:string, fallback:T){const [data,setData]=useState<T>(fallback);const [err,setErr]=useState('');const load=()=>apiClient.get<T>(path).then(setData).catch(e=>setErr(e.message));useEffect(()=>{load();},[path]);return {data,err,load};}
const sampleListings=[{id:'#123456',title:'iPhone 15 Pro Max 256GB',category:'Electronics',seller:'Jane Smith',status:'Pending',price:'$850',created:'15 min ago'},{id:'#123455',title:'2020 Toyota Camry LE',category:'Vehicles',seller:'Mike Johnson',status:'Active',price:'$16,500',created:'1 hour ago'},{id:'#123454',title:'Modern Gray Sofa Set',category:'Home & Garden',seller:'Sarah Smith',status:'Active',price:'$450',created:'2 hours ago'},{id:'#123453',title:'Office Desk Set',category:'Home & Garden',seller:'Emily Davis',status:'Rejected',price:'$350',created:'5 hours ago'}];
function App(){const [tab,setTab]=useState<Tab>('dashboard');return <div className="admin-app"><aside className="admin-sidebar"><div className="brand"><span>⌖</span><div><b>Classifieds Admin</b><small>OpenMarketplace Ops</small></div></div><nav>{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><span>{t.icon}</span>{t.label}</button>)}</nav><div className="admin-user"><div className="avatar">AD</div><div><strong>Admin</strong><small>Super Admin</small></div></div></aside><main className="admin-main"><header className="topbar"><div><h1>{tabs.find(t=>t.id===tab)?.label}</h1><p>Welcome back, Admin! Here is what is happening today.</p></div><div className="top-actions"><input placeholder="Search..."/><a href="http://localhost:5100/swagger/index.html" target="_blank">Swagger</a><div className="avatar">AD</div></div></header>{tab==='dashboard'&&<Dashboard/>}{tab==='pending'&&<Pending/>}{tab==='listings'&&<Listings/>}{tab==='categories'&&<Categories/>}{tab==='users'&&<Users/>}{tab==='banners'&&<Banners/>}{tab==='payments'&&<Payments/>}{tab==='reports'&&<Reports/>}{tab==='settings'&&<Settings/>}{tab==='health'&&<Health/>}</main></div>}
function Dashboard(){const {data}=useApi<any>('/admin/dashboard',{stats:{},recentListings:sampleListings});const s=data.stats??{};return <><div className="metric-grid">{[['Total Listings',s.totalListings??12458,'+12.5%'],['Active Listings',s.activeListings??8732,'+8.3%'],['Users',s.users??6521,'+15.7%'],['Messages',s.messages??2341,'+10.2%'],['Revenue',`$${s.revenue??24780}`,'+11.3%']].map(m=><div className="metric" key={m[0]}><span>{m[0]}</span><strong>{m[1]}</strong><em>{m[2]}</em><small>vs last 30 days</small></div>)}</div><div className="dashboard-grid"><section className="panel wide"><div className="panel-head"><h2>Listings Overview</h2><select><option>Daily</option></select></div><div className="chart-line"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></section><section className="panel"><h2>Listings by Status</h2><div className="donut"><span>12,458<small>Total</small></span></div><Legend/></section><Table title="Recent Listings" rows={data.recentListings?.length?data.recentListings:sampleListings}/><section className="panel"><h2>Top Categories</h2>{['Vehicles','Property Rentals','For Sale','Jobs','Electronics'].map((x,i)=><div className="line" key={x}><span>{x}</span><b>{[3245,2156,1987,1245,987][i]}</b></div>)}</section></div></>}
function Legend(){return <div className="legend"><span><b className="blue"></b>Active 70.1%</span><span><b className="orange"></b>Pending 10.0%</span><span><b className="purple"></b>Draft 6.9%</span><span><b className="red"></b>Rejected 3.0%</span></div>}
function Pending(){const {data,load}=useApi<any>('/admin/listings?status=Pending',{items:sampleListings});async function mod(id:string,decision:string){try{await apiClient.post(`/admin/listings/${id}/moderate`,{decision,reason:decision==='Approved'?'Approved by admin':'Rejected by admin'});load();}catch{}}const rows=data.items?.length?data.items:sampleListings;return <section className="panel"><div className="panel-head"><h2>Pending Approval</h2><div className="toolbar"><input placeholder="Search listings, sellers..."/><button>Filters</button><button>Bulk Actions</button></div></div><table><thead><tr><th><input type="checkbox"/></th><th>Listing</th><th>Category</th><th>Seller</th><th>Submitted</th><th>Actions</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><input type="checkbox"/></td><td><strong>{x.title}</strong><small>{x.id}</small></td><td>{x.category??x.categoryName}</td><td>{x.seller??'Jane Smith'}</td><td>{x.created??'15 min ago'}</td><td><button className="approve" onClick={()=>mod(x.id,'Approved')}>Approve</button><button className="reject" onClick={()=>mod(x.id,'Rejected')}>Reject</button></td></tr>)}</tbody></table></section>}
function Listings(){return <><Table title="Listings Management" rows={sampleListings}/><section className="detail-layout"><div className="phone-preview fake-photo"></div><div className="panel"><h2>Listing Details</h2><h3>iPhone 15 Pro Max 256GB — Like New</h3><p><b>$850</b> · San Jose, CA</p><p>Excellent condition. Comes with original box and charger.</p><button className="approve">Approve</button><button className="reject">Reject</button><button>More</button></div></section></>}
function Categories(){return <Table title="Categories Management" rows={['Vehicles','Property Rentals','For Sale','Jobs','Services','Electronics','Home & Garden'].map((name,i)=>({name,slug:name.toLowerCase().replace(/ /g,'-'),listings:[3245,2156,1987,1245,867,866,745][i],status:'Active'}))}/>}
function Users(){const {data}=useApi<any>('/admin/users',{items:[]});const rows=data.items?.length?data.items:[{name:'John Doe',email:'john@example.com',status:'Verified',joined:'Jun 10, 2024'},{name:'Sarah Smith',email:'sarah@example.com',status:'Verified',joined:'Jun 11, 2024'},{name:'Mike Johnson',email:'mike@example.com',status:'Banned',joined:'Jun 12, 2024'},{name:'Emily Davis',email:'emily@example.com',status:'Active',joined:'Jun 13, 2024'}];return <Table title="Users Management" rows={rows}/>}
function Banners(){return <Table title="Banners Management" rows={[{preview:'Home hero',placement:'Home - Hero',title:'Summer Sale',status:'Active',start:'Jun 1, 2024',end:'Jun 30, 2024'},{preview:'Sidebar',placement:'Listing Detail',title:'Buy & Sell Cars',status:'Active',start:'Jun 1, 2024',end:'Jun 25, 2024'}]}/>}
function Payments(){return <Table title="Payments & Transactions" rows={[{transactionId:'TXN-001',user:'John Doe',for:'Premium Upgrade',amount:'$19.99',status:'Paid',date:'Jun 30, 2024'},{transactionId:'TXN-002',user:'Jane Smith',for:'Featured Listing',amount:'$9.99',status:'Paid',date:'Jun 27, 2024'},{transactionId:'TXN-003',user:'Mike Johnson',for:'Premium Upgrade',amount:'$19.99',status:'Pending',date:'Jun 27, 2024'}]}/>}
function Reports(){return <><div className="metric-grid four"><div className="metric"><span>Total Revenue</span><strong>$24,780</strong></div><div className="metric"><span>Total Orders</span><strong>1,245</strong></div><div className="metric"><span>New Users</span><strong>812</strong></div><div className="metric"><span>Conversion Rate</span><strong>3.45%</strong></div></div><section className="panel wide"><h2>Reports & Analytics</h2><div className="chart-line tall"><i></i><i></i><i></i><i></i><i></i><i></i></div></section></>}
function Settings(){const packages=useApi<any[]>('/packages',[]);const rows=packages.data?.length?packages.data:[{name:'Free',type:'Listing',price:'$0.00',duration:'Unlimited',status:'Active'},{name:'Basic',type:'Listing',price:'$4.99',duration:'30 days',status:'Active'},{name:'Featured',type:'Promotion',price:'$9.99',duration:'7 days',status:'Active'},{name:'Premium',type:'Listing',price:'$19.99',duration:'30 days',status:'Active'}];return <Table title="Packages Management" rows={rows}/>}
function Health(){const {data,err}=useApi<any>('/admin/health',{});return <section className="panel"><h2>System Health</h2><pre>{JSON.stringify(data,null,2)}</pre>{err&&<p className="error">{err}</p>}</section>}
function Table({title,rows}:{title:string;rows:any[]}){const keys=Array.from(new Set(rows.flatMap(r=>Object.keys(r)))).slice(0,6);return <section className="panel"><div className="panel-head"><h2>{title}</h2><button>+ Add New</button></div>{rows.length?<table><thead><tr>{keys.map(k=><th key={k}>{k}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((r,i)=><tr key={r.id??i}>{keys.map(k=><td key={k}>{String(r[k]??'').slice(0,80)}</td>)}<td><button>⋯</button></td></tr>)}</tbody></table>:<div className="empty">No data</div>}</section>}
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
