import { useEffect, useState } from 'react';
import { apiClient } from '../lib/api/apiClient';
import { AdminButton, AdminTextBox } from '../components/common/AdminControls';

type City={id:string;name:string;stateCode:string;countryCode:string;geoId:string;latitude?:number;longitude?:number;sortOrder:number;selectionCount:number;isActive:boolean};
const empty={name:'',stateCode:'CA',countryCode:'US',geoId:'',latitude:'',longitude:'',sortOrder:0,isActive:true};
export function LocalitiesPage(){const[items,setItems]=useState<City[]>([]);const[q,setQ]=useState('');const[form,setForm]=useState<any>(empty);const[editing,setEditing]=useState('');const[error,setError]=useState('');
const load=async()=>{try{const d=await apiClient.get<any>(`/admin/localities?pageSize=200&q=${encodeURIComponent(q)}`);setItems(d.items??[]);}catch(e:any){setError(e.message)}};useEffect(()=>{load()},[]);
const save=async()=>{try{const payload={...form,latitude:form.latitude===''?null:Number(form.latitude),longitude:form.longitude===''?null:Number(form.longitude),sortOrder:Number(form.sortOrder)||0};if(editing)await apiClient.put(`/admin/localities/${editing}`,payload);else await apiClient.post('/admin/localities',payload);setForm(empty);setEditing('');await load();}catch(e:any){setError(e.message)}};
return <div><div className="page-title"><div><h1>California Cities</h1><p>Manual Sort Order is applied first; frequently selected cities automatically rise next.</p></div></div>{error&&<div className="notice error">{error}</div>}<div className="panel"><div className="toolbar"><AdminTextBox value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city..."/><AdminButton onClick={load}>Search</AdminButton></div><div className="form-grid"><AdminTextBox value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="City name"/><AdminTextBox value={form.sortOrder} onChange={e=>setForm({...form,sortOrder:e.target.value})} placeholder="Sort order"/><label><input type="checkbox" checked={form.isActive} onChange={e=>setForm({...form,isActive:e.target.checked})}/> Active</label><AdminButton onClick={save}>{editing?'Update':'Add city'}</AdminButton>{editing&&<AdminButton onClick={()=>{setEditing('');setForm(empty)}}>Cancel</AdminButton>}</div></div><div className="panel table-wrap"><table><thead><tr><th>City</th><th>State</th><th>Manual order</th><th>Selections</th><th>Status</th><th></th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.name}</td><td>{x.stateCode}</td><td>{x.sortOrder}</td><td>{x.selectionCount}</td><td>{x.isActive?'Active':'Hidden'}</td><td><AdminButton onClick={()=>{setEditing(x.id);setForm({...x,latitude:x.latitude??'',longitude:x.longitude??''})}}>Edit</AdminButton> <AdminButton onClick={async()=>{if(confirm(`Delete ${x.name}?`)){await apiClient.delete(`/admin/localities/${x.id}`);load()}}}>Delete</AdminButton></td></tr>)}</tbody></table></div></div>}
