name: Build Customer Docker

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Frontend Env
        run: |
          echo "NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > ./customer-web/.env

      - name: Build Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_API_BASE_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/classifieds-customer:latest \
            ./customer-web

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/classifieds-customer:latest

      - name: Deploy To Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          port: ${{ secrets.VPS_PORT }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker compose -p classifieds-customer -f /opt/classifieds/customer-compose.yml pull
            docker compose -p classifieds-customer -f /opt/classifieds/customer-compose.yml up -d --force-recreate
